[pytes]
""" Thư mục chứa test file """
testpath = tests
""" Pattern để nhận diện pytest """
python_files = test_*.py
python_classes = Test*
python_function = test_*

""" Thêm src <source> - Mã nguồn vào python path để import """
pythonpath = src

""" Markers """
markers = 
smoke: Smoke test
regression: Regression test
loginpage: Test for Login page
homepage: Test for Home page

""" Options """
addopts =
-v
--strict-marker
--html=reports/report.html
--self-contained-html
